### ISSUE TITLE
Chromium content shell - Freeze when processing std::unique_ptr<const uint8_t[]> due to IncompleteArray in template builder

### ISSUE THREAD

**Issue by vi3tL0u1s** [bkryza/clang-uml-examples#3]
Hi,

When generating a diagram with clang-uml, the process freezes at a point where it is processing a `std::unique_ptr` type that holds an incomplete array (`const uint8_t[]`). The debug logs show the following messages:

```sh
[debug] [tid 134670] [/app/clang-uml/src/class_diagram/visitor/translation_unit_visitor.cc:2088] Looking for relationships in type: std::unique_ptr<const uint8_t[]>
[debug] [tid 134670] [/app/clang-uml/src/common/visitor/template_builder.h:1047] Processing argument 0 in template class: std::unique_ptr
[debug] [tid 134670] [/app/clang-uml/src/common/visitor/template_builder.h:1148] Processing template std::unique_ptr type argument 0: const uint8_t[], IncompleteArray, const uint8_t[]
```

This issue occurs when I try to build the following diagrams:

```yaml
content_shell_renderer_client_diagram:
    type: class
    title: "Chromium Content Shell Renderer Client Diagram"
    glob:
      - content/shell/renderer/shell_content_renderer_client.cc
    generate_packages: true
    package_type: directory
    filter_mode: advanced
    include:
      namespaces:
        - ui
        - base
        - content
      paths:
        - content/shell/renderer
      context:
        - match:
            radius: 0
            pattern: "shell_content_renderer_client"
    exclude:
      elements:
        - r: ".*_test.*"

# Diagram for the Renderer Observer
content_shell_renderer_observer_diagram:
    type: class
    title: "Chromium Content Shell Renderer Observer Diagram"
    glob:
      - content/shell/renderer/shell_render_frame_observer.cc
    generate_packages: true
    package_type: directory
    filter_mode: advanced
    include:
      namespaces:
        - ui
        - base
        - content
      paths:
        - content/shell/renderer
      context:
        - match:
            radius: 0
            pattern: "shell_render_frame_observer"
    exclude:
      elements:
        - r: ".*_test.*"
```

It seems that during the template expansion for `std::unique_ptr`, the type argument const `uint8_t[]` is detected as an IncompleteArray, which might be causing the issue. 

Is there a way to bypass template processing? I just want a very general structure for the content shell's renderer.

Thank you very much,

**Comment by bkryza** [comment]
@vi3tL0u1s Thanks for reporting this. I've managed to reproduce it in Chromium codebase with `filter_mode: advanced`, however in isolated code such pointers work just fine (just no relationships from them are infererred).

I'll investigate it, however in your case the problem was with the following issues in the config file:
- you don't need to use `filter_mode: advanced` when not using `anyof` or `allof` operators, it just makes the generation much longer
- the context filter pattern must match exactly a class with fully qualified namespace or a be a regex (in your case the context filter was inactive)

I've adjusted the configs as follows:
```yaml
  content_shell_renderer_client_diagram:
      type: class
      title: "Chromium Content Shell Renderer Client Diagram"
      glob:
        - content/shell/renderer/*.cc
      generate_packages: true
      package_type: namespace
      generate_method_arguments: none
      filter_mode: basic
      include:
        namespaces:
          - ui
          - base
          - content
        context:
          - match:
              radius: 1
              pattern: content::ShellContentRendererClient
      exclude:
        elements:
          - r: ".*_test.*"
          - r: ".*Test.*"
  content_shell_renderer_client_overview_diagram:
      type: class
      title: "Chromium Content Shell Renderer Client Diagram"
      glob:
        - content/shell/renderer/*.cc
      generate_packages: true
      package_type: namespace
      generate_method_arguments: none
      filter_mode: basic
      include:
        namespaces:
          - ui
          - base
          - content
        context:
          - match:
              radius: 2
              pattern: content::ShellContentRendererClient
      exclude:
        elements:
          - r: ".*_test.*"
          - r: ".*Test.*"
        access:
          - public
          - protected
          - private
  content_shell_renderer_observer_diagram:
      type: class
      title: "Chromium Content Shell Renderer Observer Diagram"
      glob:
        - content/shell/renderer/*.cc
      generate_packages: true
      package_type: namespace
      generate_method_arguments: none
      filter_mode: basic
      include:
        namespaces:
          - ui
          - base
          - content
        context:
          - match:
              radius: 3
              pattern: content::ShellRenderFrameObserver
      exclude:
        elements:
          - r: ".*_test.*"
          - r: ".*Test.*"
        access:
          - public
          - protected
          - private
  content_shell_renderer_observer_overview_diagram:
      type: class
      title: "Chromium Content Shell Renderer Observer Diagram"
      glob:
        - content/shell/renderer/*.cc
      generate_packages: true
      package_type: namespace
      generate_method_arguments: none
      filter_mode: basic
      include:
        namespaces:
          - ui
          - base
          - content
        context:
          - match:
              radius: 2
              pattern: content::ShellRenderFrameObserver
      exclude:
        elements:
          - r: ".*_test.*"
          - r: ".*Test.*"
```

For example `content_shell_renderer_client_diagram` looks like this in PlantUML: 

![Image](https://github.com/user-attachments/assets/0bd599a5-56c2-469b-8e14-88630de852ef)

For `content_shell_renderer_client_overview_diagram` below is an example of the GraphML diagram rendered with [yED](https://www.yworks.com/products/yed) - it has much nicer layout engine for large diagrams, but at the moment the GraphML generator in `clang-uml` does not render any class members, just the nodes:

![Image](https://github.com/user-attachments/assets/c6a9950e-6b37-40ae-9060-a9c0fe4df900)

Hope this helps, you can adjust the diagram definitions further by extending the context radius or adding additional namespaces or translation units in the `glob` pattern.

**Comment by vi3tL0u1s** [comment]
Hi @bkryza,

Thank you so much for your response! I really appreciate your help, your feedback has been incredibly useful.

I have a follow-up question regarding hiding class members. As I browsed the codebase, I couldn't find an option to disable it in the config file, but I noticed a hard-coded value in the Doxyfile. Am I missing something, or is there an alternative way to configure this?

Looking forward to your insights!

**Comment by bkryza** [comment]
@vi3tL0u1s Class methods and members can be filtered using `elements` filter, but you have to use it's extended form with specified `type`, e.g. to exclude all methods containing `foo` in their name add:

```yaml
    exclude:
      elements:
        - type: method
          name:
            r: '.*foo.*'
```

There is a test case for this [t00087](https://clang-uml.github.io/md_docs_2test__cases_2t00087.html) and it is mentioned in the docs [here](https://clang-uml.github.io/md_docs_2diagram__filters.html#elements).
